<?php
/**
 * Network
 *
 * PHP version 5
 *
 * @category Class
 * @package  CapAddress\Phone
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CAP PHONE
 *
 * Cap Phone va permettre d’assister l’utilisateur lors de la validation d’un numéro de téléphone et s’assurer de la conformité syntaxique de ce dernier avant de le stocker en base de données. Le but étant de s’assurer que chaque numéro de téléphone entré en base de données est syntaxiquement correct et stocké dans un même format.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@capadresse.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CapAddress\Phone\Model;

use \ArrayAccess;
use \CapAddress\Phone\ObjectSerializer;

/**
 * Network Class Doc Comment
 *
 * @category Class
 * @package  CapAddress\Phone
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Network implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Network';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        's_country_name' => 'string',
        's_country_prefix' => 'string',
        's_net_work_name' => 'string',
        's_network_prefix' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        's_country_name' => null,
        's_country_prefix' => null,
        's_net_work_name' => null,
        's_network_prefix' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        's_country_name' => 'sCountryName',
        's_country_prefix' => 'sCountryPrefix',
        's_net_work_name' => 'sNetWorkName',
        's_network_prefix' => 'sNetworkPrefix'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        's_country_name' => 'setSCountryName',
        's_country_prefix' => 'setSCountryPrefix',
        's_net_work_name' => 'setSNetWorkName',
        's_network_prefix' => 'setSNetworkPrefix'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        's_country_name' => 'getSCountryName',
        's_country_prefix' => 'getSCountryPrefix',
        's_net_work_name' => 'getSNetWorkName',
        's_network_prefix' => 'getSNetworkPrefix'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['s_country_name'] = isset($data['s_country_name']) ? $data['s_country_name'] : null;
        $this->container['s_country_prefix'] = isset($data['s_country_prefix']) ? $data['s_country_prefix'] : null;
        $this->container['s_net_work_name'] = isset($data['s_net_work_name']) ? $data['s_net_work_name'] : null;
        $this->container['s_network_prefix'] = isset($data['s_network_prefix']) ? $data['s_network_prefix'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets s_country_name
     *
     * @return string
     */
    public function getSCountryName()
    {
        return $this->container['s_country_name'];
    }

    /**
     * Sets s_country_name
     *
     * @param string $s_country_name Nom du pays.
     *
     * @return $this
     */
    public function setSCountryName($s_country_name)
    {
        $this->container['s_country_name'] = $s_country_name;

        return $this;
    }

    /**
     * Gets s_country_prefix
     *
     * @return string
     */
    public function getSCountryPrefix()
    {
        return $this->container['s_country_prefix'];
    }

    /**
     * Sets s_country_prefix
     *
     * @param string $s_country_prefix Préfixe du pays.
     *
     * @return $this
     */
    public function setSCountryPrefix($s_country_prefix)
    {
        $this->container['s_country_prefix'] = $s_country_prefix;

        return $this;
    }

    /**
     * Gets s_net_work_name
     *
     * @return string
     */
    public function getSNetWorkName()
    {
        return $this->container['s_net_work_name'];
    }

    /**
     * Sets s_net_work_name
     *
     * @param string $s_net_work_name Nom de l’opérateur.
     *
     * @return $this
     */
    public function setSNetWorkName($s_net_work_name)
    {
        $this->container['s_net_work_name'] = $s_net_work_name;

        return $this;
    }

    /**
     * Gets s_network_prefix
     *
     * @return string
     */
    public function getSNetworkPrefix()
    {
        return $this->container['s_network_prefix'];
    }

    /**
     * Sets s_network_prefix
     *
     * @param string $s_network_prefix Préfixe de l’opérateur.
     *
     * @return $this
     */
    public function setSNetworkPrefix($s_network_prefix)
    {
        $this->container['s_network_prefix'] = $s_network_prefix;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


