<?php
/**
 * Phone
 *
 * PHP version 5
 *
 * @category Class
 * @package  CapAddress\Phone
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CAP PHONE
 *
 * Cap Phone va permettre d’assister l’utilisateur lors de la validation d’un numéro de téléphone et s’assurer de la conformité syntaxique de ce dernier avant de le stocker en base de données. Le but étant de s’assurer que chaque numéro de téléphone entré en base de données est syntaxiquement correct et stocké dans un même format.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@capadresse.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CapAddress\Phone\Model;

use \ArrayAccess;
use \CapAddress\Phone\ObjectSerializer;

/**
 * Phone Class Doc Comment
 *
 * @category Class
 * @package  CapAddress\Phone
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Phone implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'phone';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        's_tel' => 'string',
        's_indice_int' => 'string',
        's_pays' => 'string',
        's_iso_pays' => 'string',
        's_indicatif_out' => 'string',
        's_code_ret' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        's_tel' => null,
        's_indice_int' => null,
        's_pays' => null,
        's_iso_pays' => null,
        's_indicatif_out' => null,
        's_code_ret' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        's_tel' => 'sTel',
        's_indice_int' => 'sIndiceInt',
        's_pays' => 'sPays',
        's_iso_pays' => 'sIsoPays',
        's_indicatif_out' => 'sIndicatifOut',
        's_code_ret' => 'sCodeRet'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        's_tel' => 'setSTel',
        's_indice_int' => 'setSIndiceInt',
        's_pays' => 'setSPays',
        's_iso_pays' => 'setSIsoPays',
        's_indicatif_out' => 'setSIndicatifOut',
        's_code_ret' => 'setSCodeRet'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        's_tel' => 'getSTel',
        's_indice_int' => 'getSIndiceInt',
        's_pays' => 'getSPays',
        's_iso_pays' => 'getSIsoPays',
        's_indicatif_out' => 'getSIndicatifOut',
        's_code_ret' => 'getSCodeRet'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['s_tel'] = isset($data['s_tel']) ? $data['s_tel'] : null;
        $this->container['s_indice_int'] = isset($data['s_indice_int']) ? $data['s_indice_int'] : null;
        $this->container['s_pays'] = isset($data['s_pays']) ? $data['s_pays'] : null;
        $this->container['s_iso_pays'] = isset($data['s_iso_pays']) ? $data['s_iso_pays'] : null;
        $this->container['s_indicatif_out'] = isset($data['s_indicatif_out']) ? $data['s_indicatif_out'] : null;
        $this->container['s_code_ret'] = isset($data['s_code_ret']) ? $data['s_code_ret'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets s_tel
     *
     * @return string
     */
    public function getSTel()
    {
        return $this->container['s_tel'];
    }

    /**
     * Sets s_tel
     *
     * @param string $s_tel Numéro de téléphone.
     *
     * @return $this
     */
    public function setSTel($s_tel)
    {
        $this->container['s_tel'] = $s_tel;

        return $this;
    }

    /**
     * Gets s_indice_int
     *
     * @return string
     */
    public function getSIndiceInt()
    {
        return $this->container['s_indice_int'];
    }

    /**
     * Sets s_indice_int
     *
     * @param string $s_indice_int Indice national.
     *
     * @return $this
     */
    public function setSIndiceInt($s_indice_int)
    {
        $this->container['s_indice_int'] = $s_indice_int;

        return $this;
    }

    /**
     * Gets s_pays
     *
     * @return string
     */
    public function getSPays()
    {
        return $this->container['s_pays'];
    }

    /**
     * Sets s_pays
     *
     * @param string $s_pays Pays.
     *
     * @return $this
     */
    public function setSPays($s_pays)
    {
        $this->container['s_pays'] = $s_pays;

        return $this;
    }

    /**
     * Gets s_iso_pays
     *
     * @return string
     */
    public function getSIsoPays()
    {
        return $this->container['s_iso_pays'];
    }

    /**
     * Sets s_iso_pays
     *
     * @param string $s_iso_pays Code Iso3 du pays.
     *
     * @return $this
     */
    public function setSIsoPays($s_iso_pays)
    {
        $this->container['s_iso_pays'] = $s_iso_pays;

        return $this;
    }

    /**
     * Gets s_indicatif_out
     *
     * @return string
     */
    public function getSIndicatifOut()
    {
        return $this->container['s_indicatif_out'];
    }

    /**
     * Sets s_indicatif_out
     *
     * @param string $s_indicatif_out Indicatif international.
     *
     * @return $this
     */
    public function setSIndicatifOut($s_indicatif_out)
    {
        $this->container['s_indicatif_out'] = $s_indicatif_out;

        return $this;
    }

    /**
     * Gets s_code_ret
     *
     * @return string
     */
    public function getSCodeRet()
    {
        return $this->container['s_code_ret'];
    }

    /**
     * Sets s_code_ret
     *
     * @param string $s_code_ret Code Retour.
     *
     * @return $this
     */
    public function setSCodeRet($s_code_ret)
    {
        $this->container['s_code_ret'] = $s_code_ret;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


